# _+_ coding: utf-8 _+_
# Generated by Selenium IDE

import pytest
from fixture.application import Application

@pytest.fixture
def app(request):
    fixture = Application()
    request.addfinalizer(fixture.destroy)
    return fixture

def setup_method(app, method):
    app.app = Application()

def test_testcfayfi(app, w_width=1377, w_height=1020):
    # Test name: test cf ayfi
    # Step # | name | target | value | comment
    app.open_home_page()
    print("\nPage opened")
    # 2 | setWindowSize | 1377x1020 |  |
    app.driver.set_window_size(w_width, w_height)
    print("Resolution adjusted")
    # Fill group form
    app.fill_form_fields()
    print("Fields filled")

def teardown_method(app, method):
    app.app.destroy()
